# Generated by Django 3.0 on 2019-12-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDingresoDeduccion', models.PositiveIntegerField(default=0)),
                ('Fecha', models.DateTimeField(verbose_name='Fecha de transaccion')),
                ('Monto', models.FloatField()),
                ('Estado', models.BooleanField(default=True)),
                ('IDtransacionRegistrada', models.PositiveIntegerField(default=0)),
                ('IngresoDeduccion', models.CharField(default='', max_length=100)),
                ('DependeSalario', models.BooleanField(default=False)),
                ('Descripcion', models.CharField(default='', max_length=100)),
                ('Moneda', models.CharField(choices=[('1', 'DOP'), ('2', 'Dolar')], default='1', max_length=2)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.Empleado')),
            ],
        ),
    ]
