# Generated by Django 3.0 on 2019-12-07 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamentos', '0001_initial'),
        ('Puestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('Nombre', models.CharField(max_length=50)),
                ('SalarioMensual', models.FloatField()),
                ('Estado', models.BooleanField(default=True)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.Departamento')),
                ('Puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Puestos.Puesto')),
            ],
        ),
    ]
