# Generated by Django 3.0 on 2019-12-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Estado',
            new_name='EstadoEmp',
        ),
    ]
